<a href="https://colab.research.google.com/github/vedanshu786/ML-project/blob/main/Grip_Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import math

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv')
df.head(4)

   Hours  Scores
0    2.5      21
1    5.1      47
2    3.2      27
3    8.5      75

In [7]:
df.Scores =df.Scores.fillna(df.Scores.median())
df

    Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

In [12]:
reg = linear_model.LinearRegression()
reg.fit(df[['Hours']],df.Scores)

LinearRegression()

In [13]:
reg.predict([[5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"

array([51.36269036])